# Используем официальный образ Nginx из Docker Hub
FROM nginx:latest

# Копируем конфигурационные файлы Nginx в контейнер
COPY nginx.conf /etc/nginx/nginx.conf
COPY fastapi.conf /etc/nginx/conf/fastapi.conf

# Определяем порт, который Nginx будет слушать
EXPOSE 80

# Команда для запуска Nginx в фоновом режиме при запуске контейнера
CMD ["nginx", "-g", "daemon off;"]
